# Generated by Django 2.1 on 2018-08-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0003_auto_20180825_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(max_length=32),
        ),
    ]
