# Generated by Django 2.1 on 2018-08-25 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0004_auto_20180825_1047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'permissions': (('is_internal', 'Is a member of MAKE NTNU'), ('can_register_new_member', 'Can register new member'), ('can_edit_group_membership', 'Can edit the groups a member is part of, including (de)activation'))},
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
