# Generated by Django 2.1 on 2018-08-26 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('internal', '0005_auto_20180825_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberInactive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('groups', models.ManyToManyField(to='auth.Group')),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='member',
            name='inactive_data',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='internal.MemberInactive'),
        ),
    ]
