# Generated by Django 2.1 on 2018-08-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0006_auto_20180826_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberinactive',
            name='full_name',
            field=models.CharField(default='test', max_length=256),
            preserve_default=False,
        ),
    ]
