# Generated by Django 2.1 on 2018-08-26 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0007_memberinactive_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='inactive_data',
        ),
        migrations.AddField(
            model_name='memberinactive',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='internal.Member'),
        ),
    ]
