# Generated by Django 2.1 on 2018-08-27 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0009_auto_20180827_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secretfavorite',
            name='favorite',
        ),
    ]
